### ISSUE TITLE
Autoload.php

### ISSUE THREAD

**Issue by gulaandrij** [serj1chen/nova-poshta-sdk-php#14]
Сейчас при добалвлении либы через композер ставится не рабочая версия, так как есть ошибка поправленая етим комитом - https://github.com/serj1chen/nova-poshta-sdk-php/commit/c721ad342370b708a105e1cb791abefb02eedf26 . Мб стоит сделать новый тег?

**Comment by serj1chen** [comment]
Если не сложно поправьте, я приму Ваши пул реквест. У меня сейчас нет времени заниматся правками(

**Comment by gulaandrij** [comment]
Это уже исправлено, я указал ссылку на комит. Нужно только сделать тэг. Насколько я знаю - это нельзя сделать через пул реквест
