### ISSUE TITLE
Autoload.php

### ISSUE THREAD

**Issue by bruhanda** [serj1chen/nova-poshta-sdk-php#3]
У меня почему то не заработал Autoload, в методе load при формировании пути в строке был бэкслеш, помогло так

```
public static function load($className)
{
    $className = str_replace('NovaPoshta\\', '', $className);        
    $className = NOVA_POSHTA_PATH_SDK . $className . '.php';
    $className = str_replace('\\', '/', $className);
    if ((file_exists($className) === false) || (is_readable($className) === false)) {
        return false;
    }

    require($className);

    return true;
}
```

Правда я не знаю на сколько это правильное решение. 

PS:: Огромное спасибо за проделанную работу, библиотека супер!

**Comment by serj1chen** [comment]
Переделал на это: https://github.com/serj1chen/nova-poshta-sdk-php/commit/1bea3f80f9d8e5f966458ea162113346a4f7a00c Должно помочь. Спасибо за комментарий. Если не сложно проверти то что я исправил.
